name: "NVM with cache"
description: "Use Node version defined in .nvmrc and cached node_modules"
runs:
  using: "composite"
  steps:
    - name: Use Node.js
      shell: bash -l {0}
      run: nvm install

    - name: Install dependencies
      uses: bahmutov/npm-install@v1
